version: 2
updates:
  - package-ecosystem: "gradle"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "bundler"
    target-branch: "master"
    directory: "/"
    schedule:
      interval: "daily"
