name: OpenDocument-Reader-Android

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install ninja
      run: sudo apt-get install -y ninja-build
    - name: Checkout submodule
      run: git submodule update --init --recursive
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew clean assembleDebug

  test:

    runs-on: macos-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Checkout submodule
      run: git submodule update --init --recursive

    - name: brew
      run: ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
    - name: ninja
      run: brew install ninja
    - name: bundler
      run: gem install bundler
    - name: fastlane
      run: bundle install

    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 29
        target: google_apis
        arch: x86_64
        script: bundle exec fastlane tests
